# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Personal Blog
tagline:          ' A Journey to a never ending of stuff|(╯°Д°）╯'
description:      'A collection of randomness of Information that i think that is useful at least for me :D ,not a rant;</br>
    Disclaimer: The views expressed on this blog are my personal views and opinion and do not reflects views of my employer '
url:              https://sokk19xx.github.io/

author:
  name:           'Kourun'
  url:            https://www.linkedin.com/in/skourun

paginate:         5

# Custom vars
version:          0.0.1
Resume:           https://www.linkedin.com/in/skourun

github:
  repo:           https://github.com/sokk19xx



